using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;

[assembly: AssemblyTitle("Firebase.Platform")]
[assembly: AssemblyDescription(null)]
[assembly: AssemblyConfiguration(null)]
[assembly: AssemblyCompany("Google Inc.")]
[assembly: AssemblyProduct("Firebase")]
[assembly: AssemblyCopyright("Copyright 2016 Google Inc. All Rights Reserved.")]
[assembly: AssemblyTrademark(null)]
[assembly: InternalsVisibleTo("Firebase.Analytics")]
[assembly: InternalsVisibleTo("Firebase.App")]
[assembly: InternalsVisibleTo("Firebase.AppCheck")]
[assembly: InternalsVisibleTo("Firebase.Auth")]
[assembly: InternalsVisibleTo("Firebase.Crashlytics")]
[assembly: InternalsVisibleTo("Firebase.Database")]
[assembly: InternalsVisibleTo("Firebase.Firestore")]
[assembly: InternalsVisibleTo("Firebase.Functions")]
[assembly: InternalsVisibleTo("Firebase.Installations")]
[assembly: InternalsVisibleTo("Firebase.InstanceId")]
[assembly: InternalsVisibleTo("Firebase.Messaging")]
[assembly: InternalsVisibleTo("Firebase.RemoteConfig")]
[assembly: InternalsVisibleTo("Firebase.Storage")]
[assembly: InternalsVisibleTo("Firebase.TaskExtension")]
[assembly: InternalsVisibleTo("Firebase.TestLab")]
[assembly: InternalsVisibleTo("Firebase.TestLab.GameLoop")]
[assembly: InternalsVisibleTo("Firebase.FirebaseAI")]
[assembly: AssemblyVersion("1.0.0.0")]
